# Generated by Django 3.1.1 on 2021-02-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chees',
            new_name='Cheese',
        ),
    ]
